captainVersion: 4
services:
    '$$cap_appname':
        image: romancin/rutorrent-flood:$$cap_version
        environment:
            TZ: '$$cap_tz'
            PHP_TZ: '$$cap_tz'
            SSL_ENABLED: '$$enable_ssl'
            PGID: '0'
            PUID: '0'
        volumes:
            - '$$cap_appname-data:/srv/data'
        caproverExtra:
            containerHttpPort: '8080'
caproverOneClickApp:
    variables:
         - id: '$$enable_ssl'
           label: Enable SSL
           defaultValue: 'yes'
           description: 'Whether or not the container should use SSL. either, "yes" or "no". (This is separate from Caprover's SSL settings.)'
           validRegex: '/(no|yes)/'
         - id: '$$rutorrent_usr'
          label: Username for rutorrent & Flood
          defaultValue: 'admin'
          description: 'The username used to log into rutorrent & flood'
          validRegex: '/.+/'
         - id: '$$rutorrent_pw'
          label: Password for rutorrent & Flood
          defaultValue: 'hackme1'
          description: 'The password used to log into rutorrent & flood'
          validRegex: '/.+/'
        - id: '$$cap_version'
          label: romancin/rutorrent Version
          defaultValue: 'latest'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/romancin/rutorrent-flood
          validRegex: "/^([^\\s^\\/])+$/"
        - id: '$$cap_tz'
          label: Time Zone
          defaultValue: America/New_York
          description: Get yours from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          validRegex: '/.{1,}/'
    instructions:
        start: |-
            This is a completely funcional Docker image with flood, rutorrent, rtorrent, libtorrent and a lot of plugins for rutorrent, 
            like autodl-irssi, filemanager, fileshare and other useful ones.
            More details: https://github.com/romancin/rutorrent-flood-docker
        end: |-
            rutorrent-flood has been successfully deployed!
    displayName: rutorrent-flood
    isOfficial: false
    description: This is a completely funcional Docker image with flood, rutorrent, rtorrent, libtorrent and a lot of plugins for rutorrent, like autodl-irssi, filemanager, fileshare and other useful ones.
    documentation: See https://github.com/romancin/rutorrent-flood-docker
